version: '3.8'

services:
  # Servicio de PostgreSQL
  db:
    image: postgres:13
    container_name: payments_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  
  # Servicio del microservicio de autenticación
  payments-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_service
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: ${DB_PORT
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BROKER: ${KAFKA_BROKER}  # Cambia esto para que apunte al nombre del servicio de Kafka
    ports:
      - "3002:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata: