version: '3'
services:
  payment-service:
    build: .
    ports:
      - '3002:3002'
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=payment_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - postgres
    networks:
      - payment-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: payment_db
    ports:
      - '5432:5432'
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge
